# 颜色识别
enemy_color: 0  # 0:Red, 1:Blue, 2:test
enemy_type: 0 # 0:small 1:big 2:all

# 红色HSV
threshold/red:
  hue_min: 0
  hue_max: 10
  sat_min: 100
  sat_max: 255
  val_min: 50
  val_max: 255

# 蓝色
threshold/blue:
  hue_min: 100
  hue_max: 130
  sat_min: 100
  sat_max: 255
  val_min: 50
  val_max: 255

# 灯条参数
light:
  min_area: 50.0
  max_ratio: 0.6
  min_solidity: 0.7
  min_height: 14.0

# 配对参数
pair:
  light_max_angle_diff: 15.0
  light_max_height_diff_ratio: 0.5
  light_max_y_diff_ratio: 0.3
  light_min_x_diff_ratio: 0.5
  armor_min_aspect_ratio: 0.5
  armor_max_aspect_ratio: 4.8
  armor_big_armor_ratio: 3.0
  armor_small_armor_ratio: 2.0

# 处理参数
brightness_thresh: 150

# 形态学
morphology:
  # colorSegmentation函数
  open_size: 3
  close_size: 5
  # detectArmor函数
  kernel_size: 4

# 数字缩放目标像素大小 - 正方形
digit:
  big: 28
  small: 28
  threshold: 0.65

# 绘制函数 - drawDetections
draw_detect:
  e_light: true
  e_rect: true
  e_l_center: true
  e_r_center: true
  e_label: true

# 绘制函数 - drawDetections - color
# 标签为敌人颜色，不修改
# WHITE=0 BLACK RED ORANGE YELLOW GREEN BULE PURPLE=7
draw_color:
  e_light: 7
  e_rect: 5
  e_l_center: 4
  e_r_center: 3


